language: groovy

sudo: true

# from https://guides.grails.org/grails-on-travis-basics/guide/index.html
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# from https://www.deps.co/guides/travis-ci-latest-java/
matrix:
  include:
    - jdk: openjdk8
      #before_install:
      #  - rm "${JAVA_HOME}/lib/security/cacerts"
      #  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

jdk:
  - openjdk8

services:
  - mysql

# env:
#   - GRAILS_VERSION=2.5.6

# before_install:
#   - rm -rf ~/.gvm
#   - curl -s get.sdkman.io | bash
#   - source "$HOME/.sdkman/bin/sdkman-init.sh"
#   - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
#   - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  # dev null is to avoid the need for user input https://github.com/sdkman/sdkman-cli/issues/101
#   - sdk install grails $GRAILS_VERSION < /dev/null
#   - sdk use grails $GRAILS_VERSION
#   - grails -version
#   - sdk current grails

branches:
  only:
    - master

before_script:
  - chmod +x grailsw
  - mysql -e 'create database ehrserver2_test;'

#script: ./grailsw refresh-dependencies
#     && ./grailsw "test-app -integration -echoOut"
#     && ./grailsw "test-app -unit UserControllerSpec"
scritp: ./grailsw "test-app -integration -echoOut"
